# Generated by Django 4.2.7 on 2025-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Record', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GrassEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Hum', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='IoDetCount',
        ),
    ]
